### ISSUE TITLE
Light temperature capability

### ISSUE THREAD

**Issue by vincent-iQontrol** [athombv/node-homey-zigbeedriver#45]
When controlling a light bulb with a light temperature capability we get this error:

2020-07-24 14:00:58 [log] [ManagerDrivers] [filament_led] [1] set light_temperature → 1 (cluster: colorControl, endpoint: 1)
2020-07-24 14:00:58 [err] [ManagerDrivers] [filament_led] [1] Error: failed to set cluster capability value (capability: light_temperature, cluster: colorControl, value: 1) TypeError: expected_new_range_start_number
    at mapValueRange (/node_modules/homey-zigbeedriver/lib/util/index.js:37:48)
    at BulbZigbee.setParser (/node_modules/homey-zigbeedriver/lib/system/capabilities/light_temperature/colorControl.js:20:41)
    at BulbZigbee.setClusterCapabilityValue (/node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:792:43)
    at /node_modules/homey-zigbeedriver/lib/ZigBeeDevice.js:1112:19
    at BulbZigbee._onSetCapabilityValue (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js:121:11)
    at Driver._onDeviceSetCapabilityValue (/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Driver.js:101:27)
    at ManagerDrivers._onDeviceSetCapabilityValue (/opt/homey-client/node_modules/homey-apps-sdk-v3/manager/drivers.js:145:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by vincent-iQontrol** [comment]
<img width="424" alt="Schermafbeelding 2020-07-24 om 16 07 21" src="https://user-images.githubusercontent.com/26245364/88399862-cf665e80-cdc7-11ea-9801-084ee68412e9.png">

Interview with the device. Maybe this could be the source of the problem?

**Comment by RobinBol** [comment]
Hi @vincent-iQontrol , your issue is caused by a dependency on two store values which need to be set. I added documentation for this in this commit https://github.com/athombv/node-homey-zigbeedriver/commit/1939a53b011fde0503e5abe4d7044b9d92cd9181.

You can also check `ZigBeeLightDevice` since it implements similar behaviour: https://github.com/athombv/node-homey-zigbeedriver/blob/master/lib/ZigBeeLightDevice.js#L240.

**Comment by vincent-iQontrol** [comment]
I already use the ZigbeeLightDevice class

`'use strict';

const { ZigBeeLightDevice } = require('homey-zigbeedriver');
const { CLUSTER } = require('zigbee-clusters');


class BulbZigbee extends ZigBeeLightDevice {

    async onNodeInit({zclNode}) {

      this.registerCapability('onoff', CLUSTER.ON_OFF);
      this.registerCapability('dim', CLUSTER.LEVEL_CONTROL);
      this.registerCapability('light_temperature', CLUSTER.COLOR_CONTROL); // not working
    }
}

module.exports = BulbZigbee;
`

**Comment by RobinBol** [comment]
Ah I see, you should properly override `onNodeInit` if you need to do so. But if you are extending `ZigBeeLightDevice` you don't have to register the capabilities the way you do.

If you want to override `onNodeInit` do this (as the example shows):
```js
  class ZigBeeBulb extends ZigBeeLightDevice {
     async onNodeInit({zclNode, node}) {
       await super.onNodeInit({zclNode, node});
       // Do custom stuff here
     }
  }
```

But you probably don't need to that, check the implementation of `ZigBeeLightDevice` in the docs: https://athombv.github.io/node-homey-zigbeedriver/ZigBeeLightDevice.html

And for an example implementation: https://github.com/athombv/nl.klikaanklikuit.zigbee/blob/master/drivers/smart_rgb_tunable_led_bulb_E27/device.js

**Comment by vincent-iQontrol** [comment]
Thanks, this worked!
